### ISSUE TITLE
Investigate Fish shell and how it compares to ZSH

### ISSUE THREAD

**Issue by alexanderjeurissen** [alexanderjeurissen/dotfiles#24]
I'v been a long time user of zsh, but there are several things I'm dissatisfied with with zsh:

1. *Config bloat:* basic things such as autocomplete, history, syntax highlighting require a lot of configuration and setup upfront.
2. *Configuration spread*: cofiguration is spread amongst `.zshenv`, `.zshhrc`, `.zprofile`. Reasoning is to support scenario's where there is a `dumb` terminal and to reduce the amount of configuration that is loaded in such terminals. Given that most of my terminals are `--login` terminals that don't require this it ends up overcomplicating the configuration.
3. Prompt slowness: prompt speed has been hit and miss for me.

There are some ways to speed up zsh, most notably I've been looking into: 
https://carlosbecker.com/posts/speeding-up-zsh/

But I also want to explore if Fish addresses some of those pain points.

**Comment by alexanderjeurissen** [comment]
Fish vs ZSH comparison resources:

- [ ] https://medium.com/better-programming/why-i-use-fish-shell-over-bash-and-zsh-407d23293839
- [ ] https://zellwk.com/blog/bash-zsh-fish/
- [ ] https://www.reddit.com/r/linux/comments/2gfpps/why_did_you_choose_fish_shell_over_zsh/
- [ ] https://www.reddit.com/r/linuxquestions/comments/aemcmb/fish_or_zsh/
- [ ] https://dev.to/joshmedeski/why-i-switched-from-zsh-to-fish-2j17
- [ ] https://flaviocopes.com/fish-shell/

**Comment by alexanderjeurissen** [comment]
### Resources:

- https://fishshell.com/docs/current/commands.html
- https://github.com/jorgebucaran/fish-cookbook
- https://github.com/rbenv/fish-rbenv

**Comment by alexanderjeurissen** [comment]
### TODO

- [ ] Figure out a way to have performant `nodenv`

**Comment by alexanderjeurissen** [comment]
PR is live, going to test this branch for a week or so before committing.
